-- ============================================================
-- Swarme D1 Schema — Phase 9: Globalization & Analytics
-- ============================================================
-- Adds:
--   1. target_language on Projects (ISO 639-1 code for AI content generation)
--   2. images_optimized on Content_Assets (count of alt-tags generated by Vision AI)
-- ============================================================

-- ─── Projects: Add target_language ──────────────────────────
-- ISO 639-1 language code (e.g., 'en', 'fr', 'es', 'de', 'ja').
-- Determines the language the Heavy LLM generates content in.
-- Default 'en' for backwards compatibility with existing projects.
ALTER TABLE Projects ADD COLUMN target_language TEXT NOT NULL DEFAULT 'en';

-- ─── Content_Assets: Track Vision AI optimization count ─────
-- Stores how many <img> alt attributes were generated by the
-- Phase 8 vision pipeline for each published content piece.
-- Used by the Swarm ROI Dashboard to quantify ADA fixes.
ALTER TABLE Content_Assets ADD COLUMN images_optimized INTEGER NOT NULL DEFAULT 0;
