-- ============================================================
-- Migration 0005: Site Audits — Phase 11
-- Autonomous Site Audit & Assessment Engine
-- ============================================================
-- Stores deep-crawl audit results per project, produced by
-- Cloudflare Browser Rendering /crawl + Workers AI extraction.
-- Each row captures a full site health snapshot with a numeric
-- score, structured findings, and a prioritised remediation
-- roadmap generated by AI.
-- ============================================================

CREATE TABLE IF NOT EXISTS Site_Audits (
  id              TEXT PRIMARY KEY DEFAULT ('audit_' || lower(hex(randomblob(8)))),
  project_id      TEXT NOT NULL REFERENCES Projects(id) ON DELETE CASCADE,

  -- Overall health score (0–100) computed from weighted findings
  health_score    INTEGER NOT NULL DEFAULT 0,

  -- JSON array of findings: [{ category, severity, title, detail, selector? }]
  -- severity: "critical" | "high" | "medium" | "low"
  -- category: "performance" | "seo" | "accessibility" | "security" | "content"
  findings        TEXT NOT NULL DEFAULT '[]',

  -- JSON array of prioritised remediation items:
  -- [{ priority: 1-N, title, description, category, effort, impact }]
  -- effort: "low" | "medium" | "high"
  -- impact: "low" | "medium" | "high"
  roadmap         TEXT NOT NULL DEFAULT '[]',

  -- Raw page data returned by /crawl (truncated to save space)
  raw_crawl_data  TEXT,

  -- Status of the audit run
  status          TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
  error_message   TEXT,

  -- URL that was audited (project domain root by default)
  audited_url     TEXT NOT NULL,

  -- Number of pages crawled
  pages_crawled   INTEGER NOT NULL DEFAULT 0,

  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Index for fetching the latest audit per project quickly
CREATE INDEX IF NOT EXISTS idx_site_audits_project_date
  ON Site_Audits (project_id, created_at DESC);
