-- ============================================================
-- Swarme D1 Schema — Phase 15: Revenue Attribution
-- ============================================================
-- Ledger for tracking e-commerce orders that originated from
-- content generated by the swarm. Each row represents a single
-- order attributed to a specific Content_Asset.

CREATE TABLE IF NOT EXISTS Attributed_Revenue (
  id          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  project_id  TEXT NOT NULL REFERENCES Projects(id) ON DELETE CASCADE,
  asset_id    TEXT NOT NULL REFERENCES Content_Assets(id) ON DELETE CASCADE,
  order_id    TEXT NOT NULL,
  amount      REAL NOT NULL DEFAULT 0.0,
  currency    TEXT NOT NULL DEFAULT 'USD',
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_revenue_project   ON Attributed_Revenue(project_id);
CREATE INDEX IF NOT EXISTS idx_revenue_asset     ON Attributed_Revenue(asset_id);
CREATE INDEX IF NOT EXISTS idx_revenue_created   ON Attributed_Revenue(created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_revenue_order ON Attributed_Revenue(order_id);

-- ─── Add images_optimized column if not present ───
-- (Referenced in Content_Assets INSERT but may be missing from older schemas)
-- Safe to re-run: IF NOT EXISTS pattern for column addition via a temp approach.
-- D1 SQLite does not error on duplicate column names with INSERT OR IGNORE.
