-- ============================================================
-- Phase 17: Content Atomization Engine (Strict Copilot)
-- Migration 0008: Social_Drafts table
-- ============================================================
--
-- Stores social media drafts generated by the Social Agent
-- after article publication. Drafts are NEVER posted autonomously.
-- They remain in AWAITING_APPROVAL until a human reviews, edits,
-- and explicitly approves them.
--
-- Linked to Content_Assets(id) via asset_id.
-- ============================================================

CREATE TABLE IF NOT EXISTS Social_Drafts (
  id                TEXT      PRIMARY KEY,
  asset_id          TEXT      NOT NULL,
  platform          TEXT      NOT NULL CHECK (platform IN ('twitter', 'linkedin')),
  content_payload   TEXT      NOT NULL,     -- JSON: twitter = string[], linkedin = string
  status            TEXT      NOT NULL DEFAULT 'AWAITING_APPROVAL'
                              CHECK (status IN ('AWAITING_APPROVAL', 'APPROVED', 'PUBLISHED', 'REJECTED')),
  created_at        DATETIME  NOT NULL DEFAULT (datetime('now')),
  updated_at        DATETIME  NOT NULL DEFAULT (datetime('now')),

  -- Foreign key relationship (enforced at application layer for D1)
  -- References Content_Assets(id)
  UNIQUE(asset_id, platform)
);

-- Index for the Social Queue UI (fetch pending drafts quickly)
CREATE INDEX IF NOT EXISTS idx_social_drafts_status
  ON Social_Drafts (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_drafts_asset
  ON Social_Drafts (asset_id);

-- Trigger to auto-update the updated_at timestamp
CREATE TRIGGER IF NOT EXISTS trg_social_drafts_updated
  AFTER UPDATE ON Social_Drafts
  FOR EACH ROW
BEGIN
  UPDATE Social_Drafts
  SET updated_at = datetime('now')
  WHERE id = NEW.id;
END;
